config/routes.rb
Rails.application.routes.draw do
    use_doorkeeper
    devise_for :users
    resources :pets do
        resources :comments, only: [:index, :create, :update, :destroy]
    end
    namespace :api do
        namespace :v1 do
            resources :profiles do
                get :me, on: :collection
                get :all, on: :collection
            end
            resources :pets do
                resources :comments
            end
        end
    end
    root to: 'pets#index'
end

app/models/ability.rb
class Ability
    include CanCan::Ability

    attr_reader :user

    def initialize(user)
        @user = user
        if user
            user.admin? ? admin_abilities : user_abilities
        else
            guest_abilities
        end
    end

    def guest_abilities
        can :read, :all
    end

    def admin_abilities
        can :manage, :all
    end

    def user_abilities
        guest_abilities
        can :create, :all
        can :update, [Pet, Comment], user: user
        can :destroy, [Pet, Comment], user: user
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :pet

    validates :body, :user_id, :pet_id, presence: true

    scope :with_id, -> { where.not(id: nil) }
end

app/models/pet.rb
class Pet < ActiveRecord::Base
    mount_uploader :image, ImageUploader

    belongs_to :user
    has_many :comments

    validates :name, :caption, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :pets
    has_many :comments
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
    check_authorization
    before_action :doorkeeper_authorize!

    respond_to :json

    protected
    def current_resource_owner
        @current_resource_owner ||= User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
    end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::BaseController
    authorize_resource Comment

    before_action :pet_find, only: [:index, :create]

    def index
        @comments = @pet.comments
        respond_with @comments
    end

    def show
        @comment = Comment.find(params[:id])
        respond_with @comment, serializer: CommentSerializer
    end

    def create
        @comment = @pet.comments.create(comment_params.merge(user: current_resource_owner))
        respond_with @comment, location: -> { api_v1_pet_comment_path(@pet, @comment) }
    end

    private
    def pet_find
        @pet = Pet.find(params[:pet_id])
    end

    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/api/v1/pets_controller.rb
class Api::V1::PetsController < Api::V1::BaseController
    authorize_resource Pet

    def index
        @pets = Pet.all
        respond_with @pets
    end

    def show
        @pet = Pet.find(params[:id])
        respond_with @pet, serializer: PetSerializer::Pet
    end

    def create
        @pet = current_resource_owner.pets.create(pet_params)
        respond_with @pet
    end

    private
    def pet_params
        params.require(:pet).permit(:name, :caption, :image)
    end
end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < Api::V1::BaseController
    authorize_resource User, user: @current_resource_owner

    def me
        respond_with current_resource_owner
    end

    def all
        respond_with profiles: User.where.not(id: current_resource_owner)
    end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
    self.responder = ApplicationResponder
    respond_to :html, :json

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    rescue_from CanCan::AccessDenied do |exception|
        redirect_to root_url
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: :index
    before_action :pet_find, only: [:index, :create]
    before_action :comment_find, except: [:index, :create]

    respond_to :js
    authorize_resource

    def index
        respond_with(@comments = ActiveModel::ArraySerializer.new(@pet.comments.includes(:user).with_id.order(id: :desc), each_serializer: CommentSerializer).to_json)
    end

    def create
        @comment = @pet.comments.create(comment_params.merge(user: current_user))
        render nothing: true
    end

    def update
        @comment.update(comment_params) if @comment.user_id == current_user.id || current_user.admin
        respond_with @comment
    end

    def destroy
        if @comment.user_id == current_user.id || current_user.admin
            respond_with(@comment.destroy)
        else
            render nothing: true
        end
    end

    private
    def pet_find
        @pet = Pet.find(params[:pet_id])
    end

    def comment_find
        @comment = Comment.find(params[:id])
    end

    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :pet_find, only: [:show, :edit, :update, :destroy]
    before_action :build_comment, only: :show

    respond_to :js, only: [:update, :destroy]
    authorize_resource

    def index
        respond_with(@pets = Pet.all)
    end

    def show
        respond_with @pet
    end

    def new
        respond_with(@pet = Pet.new)
    end

    def create
        respond_with(@pet = Pet.create(pet_params.merge(user: current_user)))
    end

    def edit
        respond_with @pet
    end

    def update
        @pet.update(pet_params) if @pet.user_id == current_user.id || current_user.admin
        respond_with @pet
    end

    def destroy
        if @pet.user_id == current_user.id || current_user.admin
            respond_with(@pet.destroy)
        else
            render nothing: true
        end
    end

    private
    def pet_find
        @pet = Pet.find(params[:id])
    end

    def build_comment
        @comment = @pet.comments.build
    end

    def pet_params
        params.require(:pet).permit(:name, :caption, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/update.js.erb
$('#edit_comment_<%= @comment.id %>').hide();
$('#<%= @comment.id %>').show();
$('#comment_<%= @comment.id %> .body').html('<%= @comment.body %>');

app/views/layouts/application.html.slim
doctype html
html
    head
        meta charset='utf-8'
        meta content='width=device-width, initial-scale=1.0' name='viewport'
        title MeowMeow
        = stylesheet_link_tag 'application', media: 'all'
        = javascript_include_tag 'application'
        = csrf_meta_tags
    body
        .row
            .columns.medium-8
                = yield
            .columns.medium-4
                - if current_user
                    p= "Login as #{current_user.email}"
                    p= link_to 'Logoff', destroy_user_session_path, method: :delete, class: 'button', id: 'destroy'
                - else
                    #login
                        p Authentification
                        = simple_form_for(User.new, as: :user, url: session_path(:user)) do |f|
                            p= f.input :email, autofocus: true, label: false
                            p= f.input :password, autocomplete: 'off', label: false
                            p= f.button :submit, 'Login', class: 'button', id: 'authorization'
                    #signup
                        p Registration
                        = simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f|
                            p= f.input :email, required: true, label: false, placeholder: 'Email'
                            p= f.input :password, required: true, label: false, placeholder: 'Password'
                            p= f.input :password_confirmation, autocomplete: 'off', required: true, label: false, placeholder: 'Password Confirm'
                            p=  f.button :submit, 'Sign Up', class: 'button', id: 'registration'

app/views/pets/_form.html.slim
.columns.medium-6
    h2 Pet's form
    = simple_form_for @pet do |f|
        p= f.input :name, placeholder: 'Enter name'
        p= f.input :caption, placeholder: 'Enter caption'
        p= f.file_field :image
        p= f.submit 'Submit', class: 'button'

app/views/pets/destroy.js.erb
$('#pet_<%= @pet.id %>').remove();

app/views/pets/edit.html.slim
= render 'form'

app/views/pets/index.html.slim
h1 Welcome to MeowMeow system
- if current_user
    = link_to 'Add pet', new_pet_path, class: 'button'
- @pets.each do |pet|
    .row id="pet_#{pet.id}"
        h2= "Pet's name - #{pet.name}"
        .pet
            - unless pet.image.blank?
                p= image_tag pet.image.thumb, class: 'img-responsive'
            p= pet.caption
            p
                = link_to 'Show', pet_path(pet), class: 'button'
                - if can?(:update, pet)
                    = link_to 'Edit', edit_pet_path(pet), class: 'button'
                - if can?(:destroy, pet)
                    = link_to 'Destroy', pet_path(pet), method: :delete, class: 'button', remote: true

app/views/pets/show.html.slim
h1= @pet.name
p.pet_image= image_tag @pet.image
p.pet_author
    q= @pet.user.email
p= @pet.caption
#comments
    - if current_user
        = react_component('CommentBox', url: "/pets/#{@pet.id}/comments.json", user: true)
    - else
        = react_component('CommentBox', url: "/pets/#{@pet.id}/comments.json", user: false)